version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:1234"  # Exposes port 1234 of the container to port 1234 on the host
    volumes:
      - .:/workspace  # Mounts the current directory into /workspace in the container
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"  # This maps 'host.docker.internal' to the host machine's IP
    command: tail -f /dev/null  # Keeps the container running
